name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        # you might add flake8/black, etc
        flake8 . || true
    - name: Run tests
      run: |
        pytest -q --disable-warnings --maxfail=1
    - name: Train baseline model
      run: |
        MODE=baseline MODEL_VERSION=v0.1 python train.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: models-v0.1
        path: models

  smoke:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Load model artifact
      uses: actions/download-artifact@v3
      with:
        name: models-v0.1
        path: models
    - name: Run smoke test
      run: |
        pip install -r requirements.txt
        python - <<EOF
import requests
# You might start a local server (not trivial in Actions) or test model API functions
# For simplicity: import model class & predict
from app.model import DiabetesModel
m = DiabetesModel(model_path="models/model_v0.1.joblib")
print("Prediction:", m.predict({k:0.0 for k in ["age","sex","bmi","bp","s1","s2","s3","s4","s5","s6"]}))
EOF
