name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train model for this version
      run: |
        # Derive version from tag
        echo "MODEL_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        if [[ "${GITHUB_REF#refs/tags/}" == "v0.1" ]]; then
          echo "MODE=baseline" >> $GITHUB_ENV
        else
          echo "MODE=improved" >> $GITHUB_ENV
        fi
        python train.py
    - name: Build Docker image
      run: |
        TAG=${{ github.repository }}:${GITHUB_REF#refs/tags/}
        docker build -t $TAG .
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: |
        TAG=ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}
        docker tag ${{ github.repository }}:${GITHUB_REF#refs/tags/} $TAG
        docker push $TAG
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body_path: CHANGELOG.md
